<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<div class="overlay" style="position: fixed;width: 100vw;height: 100vh;display: flex;">
    <img style="margin: auto;display: block; width: 15%" src="<?=$block->getViewFileUrl('Magenest_Worldpay::images/loading.gif') ?>" />
</div>
<script>
    jQuery(document).ready( function() {
            var PaRes = '<?= $block->getPaRes()?>';
        jQuery.ajax({
                type: "POST",
                url: '<?php echo $block->getBaseUrl()?>worldpay/threeds/process?isAjax=true',
                data: {
                    PaRes: PaRes,
                },
                showLoader: true
            }).done(function (response) {
                jQuery('body').html(response);
            });
    });
</script>