<?php
$saveCardEnabled = $block->saveCardEnabled();
if ($saveCardEnabled) {
	$savedCards = $block->getSavedCards();
} else {
	$savedCards = [];
}
?>
<?php foreach($savedCards as $savedCard): ?>

  <p><?php echo $savedCard['cardType']; ?> <?php echo $savedCard['number']; ?> - <a href="<?php echo $block->getDeleteUrl($savedCard['token']); ?>">Delete</a></p>

<?php endforeach; ?>


<?php if (!count($savedCards)): ?>
<p>You don't have any saved cards</p>
<?php endif; ?>